services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # restart: always
    # network_mode: host
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ../docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MTSQL_PASSWORD: "123123" # 业务库密码
    ports:
      - 3306:3306
      
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    # restart: always
    # network_mode: host
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
    ports:
      - 6379:6379
  # web:
  #   image: xyhelper/xyhelper-web
  #   container_name: xyhelper-web
  #   restart: always
  #   network_mode: host

  #   environment:
  #     PORT: 8888
  #     BASE_URI: http://127.0.0.1:8001
  new-api:
    image: calciumion/new-api:latest
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/new-api:/data
    network_mode: host
    # ports:
    #   - 3000:3000

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    restart: always
    environment:
      OPENAI_API_KEY: "sk-xyhelper"
      CODE: "xyhelper"
      BASE_URL: "http://172.18.0.1:3000"
    ports:
      - 3001:3000
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    network_mode: host
    environment:
      PORT: 4000
      OPENAI_API_KEY: "xyhelper"
      OPENAI_API_BASE_URL: "http://127.0.0.1:8001/v1"

    volumes:
      - ./data/open-webui:/app/backend/data
    # ports:
    #   - 3000:8080